### PR TITLE
Grammar corrections; clarify, make easier to read

### PR DESCRIPTION
**Pull request by some4**
Fixes #

Changes:
-

Does this change need to mentioned in CHANGELOG.md?

Yes | No

edit: first time making a commit in over three months just testing things out

### CODE REVIEW

**Comment by some4** [comment]
Since the README is the introduction page: we want readers to have a broad overview using the least amount of words.  The further they read, the more detailed things should get.

**Comment by olemis** [comment]
@some4 Feel free to follow skycoin/skycoin structure . The relevant parts , of course ...

**Comment by olemis** [comment]
@olemis the README , I mean

**Comment by some4** [comment]
@olemis I briefly went over build.sh today and have an overall idea of what to add; very nice using a .conf.  I'll edit Building_Skybian.md with the changes.

**Comment by some4** [comment]
@olemis I think it's better if I merge my changes and then write about it after

**Comment by olemis** [comment]
@some4 PR's always point at branches in skycoin org . I edited the base . I requested a review from @stdevPavelmc .

**Comment by olemis** [comment]
Indeed I can not edit the base to select a branch in `skycoin/skybian` . Please create a new one with the correct branch . Thanks in advance

**Pull request closed without merging**
